extern "C" {
    fn get_archive_empty_defined_param() -> archive_empty_defined_param;
    
    fn get_archive_iso9660_defined_param() -> archive_iso9660_defined_param;
    
    fn get_archive_lha_defined_param() -> archive_lha_defined_param;
    
    fn get_archive_raw_defined_param() -> archive_raw_defined_param;

    fn get_archive_rar_defined_param() -> archive_rar_defined_param;

    fn get_archive_rar5_defined_param() -> archive_rar5_defined_param;

    fn get_archive_acl_defined_param() -> archive_acl_defined_param;
    fn get_archive_ar_defined_param() -> archive_ar_defined_param;

    fn get_archive_warc_defined_param() -> archive_warc_defined_param;

    fn get_archive_xar_defined_param() ->archive_xar_defined_param;

    fn get_archive_tar_defined_param() ->archive_tar_defined_param;

    fn get_archive_by_code_defined_param() -> archive_by_code_defined_param;

    fn get_archive_cab_defined_param() -> archive_cab_defined_param;

    fn get_archive_mtree_defined_param() -> archive_mtree_defined_param;

    fn get_archive_cpio_defined_param() -> archive_cpio_defined_param;
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct archive_empty_defined_param {
    pub archive_read_magic: libc::c_uint,
    pub archive_state_new: libc::c_uint,
    pub archive_format_empty: libc::c_int,
    pub archive_eof: libc::c_int,
}

#[derive(Debug, Copy, Clone)]
#[repr(C)]
pub struct archive_iso9660_defined_param {
    pub archive_read_magic: libc::c_uint,
    pub archive_state_new: libc::c_uint,
    pub enomem: libc::c_int,
    pub iso9660_magic: libc::c_int,
    pub logical_block_size: libc::c_int,
    pub reserved_area: libc::c_int,
    pub archive_format_iso9660: libc::c_int,
    pub archive_format_iso9660_rockridge: libc::c_int,
    pub archive_errno_misc: libc::c_int,
    pub archive_ok: libc::c_int,
    pub archive_fatal: libc::c_int,
    pub archive_warn: libc::c_int,
    pub archive_failed: libc::c_int,
    pub archive_errno_file_format: libc::c_int,
    pub archive_eof: libc::c_int,
    pub ae_ifmt: libc::c_int,
    pub ae_iflnk: libc::c_int,
    pub ae_ifdir: libc::c_int,
    pub ae_ifreg: libc::c_int,
    pub utf16_name_max: libc::c_int,
    pub system_area_block: libc::c_int,
    pub seek_set: libc::c_int,
    pub dr_extent_offset: libc::c_int,
    pub dr_extent_size: libc::c_int,
    pub dr_ext_attr_length_offset: libc::c_int,
    pub dr_ext_attr_length_size: libc::c_int,
    pub dr_size_offset: libc::c_int,
    pub dr_size_size: libc::c_int,
    pub dr_length_offset: libc::c_int,
    pub dr_length_size: libc::c_int,
    pub dr_date_offset: libc::c_int,
    pub dr_flags_offset: libc::c_int,
    pub dr_flags_size: libc::c_int,
    pub dr_file_unit_size_offset: libc::c_int,
    pub dr_file_unit_size_size: libc::c_int,
    pub dr_interleave_offset: libc::c_int,
    pub dr_interleave_size: libc::c_int,
    pub dr_name_len_offset: libc::c_int,
    pub dr_name_len_size: libc::c_int,
    pub dr_name_offset: libc::c_int,
    pub dr_volume_sequence_number_offset: libc::c_int,
    pub dr_volume_sequence_number_size: libc::c_int,
    pub svd_type_offset: libc::c_int,
    pub svd_reserved1_offset: libc::c_int,
    pub svd_reserved1_size: libc::c_int,
    pub svd_reserved2_offset: libc::c_int,
    pub svd_reserved2_size: libc::c_int,
    pub svd_reserved3_offset: libc::c_int,
    pub svd_reserved3_size: libc::c_int,
    pub svd_logical_block_size_offset: libc::c_int,
    pub svd_volume_space_size_offset: libc::c_int,
    pub svd_file_structure_version_offset: libc::c_int,
    pub svd_type_l_path_table_offset: libc::c_int,
    pub svd_type_m_path_table_offset: libc::c_int,
    pub svd_root_directory_record_offset: libc::c_int,
    pub svd_escape_sequences_offset: libc::c_int,
    pub pvd_type_offset: libc::c_int,
    pub pvd_version_offset: libc::c_int,
    pub pvd_reserved1_offset: libc::c_int,
    pub pvd_reserved2_offset: libc::c_int,
    pub pvd_reserved2_size: libc::c_int,
    pub pvd_reserved3_offset: libc::c_int,
    pub pvd_reserved3_size: libc::c_int,
    pub pvd_reserved4_offset: libc::c_int,
    pub pvd_reserved4_size: libc::c_int,
    pub pvd_reserved5_offset: libc::c_int,
    pub pvd_reserved5_size: libc::c_int,
    pub pvd_logical_block_size_offset: libc::c_int,
    pub pvd_volume_space_size_offset: libc::c_int,
    pub pvd_file_structure_version_offset: libc::c_int,
    pub pvd_type_1_path_table_offset: libc::c_int,
    pub pvd_type_m_path_table_offset: libc::c_int,
    pub pvd_root_directory_record_offset: libc::c_int,
}

#[derive(Debug, Copy, Clone)]
#[repr(C)]
pub struct archive_lha_defined_param {
    pub archive_read_magic: libc::c_uint,
    pub archive_state_new: libc::c_uint,
    pub enomem: libc::c_int,
    pub h_method_offset: libc::c_int,
    pub h_level_offset: libc::c_int,
    pub h_attr_offset: libc::c_int,
    pub h_size: libc::c_int,
    pub archive_failed: libc::c_int,
    pub archive_errno_misc: libc::c_int,
    pub archive_ok: libc::c_int,
    pub archive_fatal: libc::c_int,
    pub archive_warn: libc::c_int,
    pub archive_errno_file_format: libc::c_int,
    pub archive_format_lha: libc::c_int,
    pub archive_eof: libc::c_int,
    pub ae_ifmt: libc::c_int,
    pub ae_iflnk: libc::c_int,
    pub ae_ifdir: libc::c_int,
    pub ae_ifreg: libc::c_int,
    pub atime_is_set: libc::c_int,
    pub birthtime_is_set: libc::c_int,
    pub crc_is_set: libc::c_int,
    pub unix_mode_is_set: libc::c_int,
    pub h0_fixed_size: libc::c_int,
    pub h0_header_size_offset: libc::c_int,
    pub h0_header_sum_offset: libc::c_int,
    pub h0_comp_size_offset: libc::c_int,
    pub h0_orig_size_offset: libc::c_int,
    pub h0_dos_time_offset: libc::c_int,
    pub h0_name_len_offset: libc::c_int,
    pub h0_file_name_offset: libc::c_int,
    pub h1_header_size_offset: libc::c_int,
    pub h1_header_sum_offset: libc::c_int,
    pub h1_comp_size_offset: libc::c_int,
    pub h1_orig_size_offset: libc::c_int,
    pub h1_dos_time_offset: libc::c_int,
    pub h1_name_len_offset: libc::c_int,
    pub h1_file_name_offset: libc::c_int,
    pub h1_fixed_size: libc::c_int,
    pub h2_header_size_offset: libc::c_int,
    pub h2_comp_size_offset: libc::c_int,
    pub h2_orig_size_offset: libc::c_int,
    pub h2_time_offset: libc::c_int,
    pub h2_crc_offset: libc::c_int,
    pub h2_fixed_size: libc::c_int,
    pub h3_field_len_offset: libc::c_int,
    pub h3_comp_size_offset: libc::c_int,
    pub h3_orig_size_offset: libc::c_int,
    pub h3_time_offset: libc::c_int,
    pub h3_crc_offset: libc::c_int,
    pub h3_header_size_offset: libc::c_int,
    pub h3_fixed_size: libc::c_int,
    pub ext_header_crc: libc::c_int,
    pub ext_filename: libc::c_int,
    pub ext_utf16_filename: libc::c_int,
    pub ext_directory: libc::c_int,
    pub ext_utf16_directory: libc::c_int,
    pub ext_dos_attr: libc::c_int,
    pub ext_timestamp: libc::c_int,
    pub ext_filesize: libc::c_int,
    pub ext_codepage: libc::c_int,
    pub ext_unix_mode: libc::c_int,
    pub ext_unix_gid_uid: libc::c_int,
    pub ext_unix_gname: libc::c_int,
    pub ext_unix_uname: libc::c_int,
    pub ext_unix_mtime: libc::c_int,
    pub ext_os2_new_attr: libc::c_int,
    pub ext_new_attr: libc::c_int,
    pub ext_timezone: libc::c_int,
    pub epoc_time: libc::c_ulonglong,
    pub pt_bitlen_size: libc::c_int,
    pub lt_bitlen_size: libc::c_int,
    pub st_get_literal: libc::c_int,
    pub st_rd_block: libc::c_int,
    pub st_rd_pt_1: libc::c_int,
    pub st_rd_pt_2: libc::c_int,
    pub st_rd_pt_3: libc::c_int,
    pub st_rd_pt_4: libc::c_int,
    pub st_rd_literal_1: libc::c_int,
    pub st_rd_literal_2: libc::c_int,
    pub st_rd_literal_3: libc::c_int,
    pub st_rd_pos_data_1: libc::c_int,
    pub st_get_pos_1: libc::c_int,
    pub st_get_pos_2: libc::c_int,
    pub st_copy_data: libc::c_int,
    pub uchar_max: libc::c_int,
    pub minmatch: libc::c_int,
    pub cache_bits: libc::c_int,
    pub htbl_bits: libc::c_int,
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct archive_raw_defined_param {
    pub archive_read_magic: libc::c_uint,
    pub archive_state_new: libc::c_uint,
    pub archive_format_raw: libc::c_int,
    pub enomem: libc::c_int,
    pub archive_ok: libc::c_int,
    pub archive_eof: libc::c_int,
    pub archive_fatal: libc::c_int,
    pub ae_ifreg: libc::c_uint,
}

#[derive(Debug, Copy, Clone)]
#[repr(C)]
pub struct archive_rar_defined_param {
    pub cache_bits: libc::c_int,
    pub archive_errno_file_format: libc::c_int,
    pub archive_fatal: libc::c_int,
    pub archive_ok: libc::c_int,
    pub archive_read_format_caps_encrypt_data: libc::c_int,
    pub archive_read_format_caps_encrypt_metadata: libc::c_int,
    pub archive_read_format_encryption_dont_know: libc::c_int,
    pub archive_failed: libc::c_int,
    pub archive_errno_misc: libc::c_int,
    pub archive_warn: libc::c_int,
    pub archive_format_rar: libc::c_int,
    pub archive_eof: libc::c_int,
    pub mark_head: libc::c_int,
    pub main_head: libc::c_int,
    pub mhd_encryptver: libc::c_int,
    pub mhd_password: libc::c_int,
    pub file_head: libc::c_int,
    pub comm_head: libc::c_int,
    pub av_head: libc::c_int,
    pub sub_head: libc::c_int,
    pub protect_head: libc::c_int,
    pub sign_head: libc::c_int,
    pub endarc_head: libc::c_int,
    pub hd_add_size_present: libc::c_int,
    pub newsub_head: libc::c_int,
    pub compress_method_store: libc::c_int,
    pub compress_method_fastest: libc::c_int,
    pub compress_method_fast: libc::c_int,
    pub compress_method_normal: libc::c_int,
    pub compress_method_good: libc::c_int,
    pub compress_method_best: libc::c_int,
    pub mhd_volume: libc::c_int,
    pub fhd_split_after: libc::c_int,
    pub seek_cur: libc::c_int,
    pub seek_end: libc::c_int,
    pub seek_set: libc::c_int,
    pub fhd_split_before: libc::c_int,
    pub fhd_solid: libc::c_int,
    pub fhd_password: libc::c_int,
    pub fhd_large: libc::c_int,
    pub enomem: libc::c_int,
    pub fhd_unicode: libc::c_int,
    pub os_msdos: libc::c_int,
    pub os_os2: libc::c_int,
    pub os_win32: libc::c_int,
    pub file_attribute_directory: libc::c_int,
    pub ae_ifdir: libc::c_int,
    pub s_ixusr: libc::c_int,
    pub s_ixgrp: libc::c_int,
    pub s_ixoth: libc::c_int,
    pub ae_ifreg: libc::c_int,
    pub s_irusr: libc::c_int,
    pub s_iwusr: libc::c_int,
    pub s_irgrp: libc::c_int,
    pub s_iroth: libc::c_int,
    pub os_unix: libc::c_int,
    pub os_mac_os: libc::c_int,
    pub os_beos: libc::c_int,
    pub unp_buffer_size: libc::c_int,
    pub ae_ifmt: libc::c_int,
    pub ae_iflnk: libc::c_int,
    pub ns_unit: libc::c_int,
    pub max_compress_depth: libc::c_int,
    pub int64_max: libc::c_longlong,
    pub max_symbols: libc::c_int,
    pub max_symbol_length: libc::c_int,
    pub huffman_table_size: libc::c_int,
    pub maincode_size: libc::c_int,
    pub offsetcode_size: libc::c_int,
    pub lowoffsetcode_size: libc::c_int,
    pub lengthcode_size: libc::c_int,
    pub dictionary_max_size: libc::c_int,
}

#[derive(Debug, Copy, Clone)]
#[repr(C)]
pub struct archive_rar5_defined_param {
    pub archive_ok: libc::c_int,
    pub enomem: libc::c_int,
    pub archive_fatal: libc::c_int,
    pub archive_errno_file_format: libc::c_int,
    pub archive_errno_programmer: libc::c_int,
    pub archive_retry: libc::c_int,
    pub archive_warn: libc::c_int,
    pub archive_format_rar_v5: libc::c_int,
    pub archive_eof: libc::c_int,
    pub max_name_in_bytes: libc::c_int,
    pub max_name_in_chars: libc::c_int,
    pub ae_iflnk: libc::c_int,
    pub redir_symlink_is_dir: libc::c_int,
    pub ae_symlink_type_directory: libc::c_int,
    pub ae_symlink_type_file: libc::c_int,
    pub ae_ifreg: libc::c_int,
    pub owner_maxnamelen: libc::c_int,
    pub owner_user_name: libc::c_int,
    pub owner_group_name: libc::c_int,
    pub owner_user_uid: libc::c_int,
    pub owner_group_gid: libc::c_int,
    pub ae_ifdir: libc::c_int,
    pub uint_max: libc::c_int,
    pub huff_nc: libc::c_int,
    pub huff_bc: libc::c_int,
    pub huff_table_size: libc::c_int,
    pub huff_dc: libc::c_int,
    pub huff_ldc: libc::c_int,
    pub huff_rc: libc::c_int,
    pub int_max: libc::c_int,
    pub archive_failed: libc::c_int,
    pub archive_read_format_encryption_unsupported: libc::c_int,
}

#[derive(Debug, Copy, Clone)]
#[repr(C)]
pub struct archive_acl_defined_param{
    pub archive_ok: libc::c_int,
    pub archvie_failed: libc::c_int,
	pub archive_fatal: libc::c_int,
	pub archive_warn: libc::c_int,
	pub archive_eof: libc::c_int,
	pub enomem: libc::c_int,
	pub archive_entry_acl_append_data: libc::c_int,
	pub archive_entry_acl_delete: libc::c_int,
	pub archive_entry_acl_delete_child: libc::c_int,
	pub archive_entry_acl_read_attributes: libc::c_int,
	pub archive_entry_acl_read_named_attrs: libc::c_int,
	pub archive_entry_acl_read: libc::c_int,
	pub archive_entry_acl_read_data: libc::c_int,
	pub archive_entry_acl_write: libc::c_int,
	pub archive_entry_acl_write_named_attrs: libc::c_int,
	pub archive_entry_acl_write_attributes: libc::c_int,
	pub archive_entry_acl_write_owner: libc::c_int,
	pub archive_entry_acl_synchronize: libc::c_int,
	pub archive_entry_acl_write_data: libc::c_int,
	pub archive_entry_acl_execute: libc::c_int,
	pub archive_entry_acl_everyone: libc::c_int,
	pub archive_entry_acl_mask: libc::c_int,
	pub archive_entry_acl_other: libc::c_int,
	pub archive_entry_acl_user: libc::c_int,
	pub archive_entry_acl_group: libc::c_int,
	pub archive_entry_acl_user_obj: libc::c_int,
	pub archive_entry_acl_group_obj: libc::c_int,
	pub archive_entry_acl_type_allow: libc::c_int,
	pub archive_entry_acl_type_alram: libc::c_int,
	pub archive_entry_acl_type_audit: libc::c_int,
	pub archive_entry_acl_type_deny: libc::c_int,
	pub archive_entry_acl_type_nfs4: libc::c_int,
	pub archive_entry_acl_type_posix1e: libc::c_int,
	pub archive_entry_acl_type_access: libc::c_int,
	pub archive_entry_acl_type_default: libc::c_int,
	pub archive_entry_acl_perms_nfs4: libc::c_int,
	pub archive_entry_acl_perms_posix1e: libc::c_int,
	pub archive_entry_acl_inheritance_nfs4: libc::c_int,
	pub archive_entry_acl_style_compact: libc::c_int,
	pub archive_entry_acl_style_extra_id: libc::c_int,
	pub archive_entry_acl_style_solaris: libc::c_int,
	pub archive_entry_acl_style_mark_default: libc::c_int,
	pub archive_entry_acl_style_separator_comma: libc::c_int,
	pub archive_entry_acl_entry_file_inherit: libc::c_int,
	pub archive_entry_acl_entry_directory_inherit: libc::c_int,
	pub archive_entry_acl_entry_inherit_only: libc::c_int,
	pub archive_entry_acl_entry_no_propagate_inherit: libc::c_int,
	pub archive_entry_acl_entry_successful_access: libc::c_int,
	pub archive_entry_acl_entry_failed_access: libc::c_int,
	pub archive_entry_acl_entry_inherited: libc::c_int,
	pub archive_entry_acl_read_acl:libc::c_int,
	pub archive_entry_acl_write_acl:libc::c_int,
}


#[derive(Debug, Copy, Clone)]
#[repr(C)]
pub struct archive_ar_defined_param {
    pub archive_read_magic: libc::c_uint,
    pub archive_state_new: libc::c_uint,
    pub enomem: libc::c_int,
    pub archive_ok: libc::c_int,
    pub einval: libc::c_int,
    pub archive_fatal: libc::c_int,
    pub ar_name_size: libc::c_int,
    pub ar_name_offset: libc::c_int,
    pub archive_format_ar: libc::c_int,
    pub archive_format_ar_bsd: libc::c_int,
    pub archive_format_ar_gnu: libc::c_int,
    pub archive_errno_misc: libc::c_int,
    pub ae_ifreg: libc::c_int,
    pub ar_size_offset: libc::c_int,
    pub ar_size_size: libc::c_int,
    pub archive_eof: libc::c_int,
    pub ar_date_offset: libc::c_int,
    pub ar_date_size: libc::c_int,
    pub ar_uid_offset: libc::c_int,
    pub ar_uid_size: libc::c_int,
    pub ar_gid_offset: libc::c_int,
    pub ar_gid_size: libc::c_int,
    pub ar_mode_offset: libc::c_int,
    pub ar_mode_size: libc::c_int,
    pub uint64_max: libc::c_ulong,
    pub ar_fmag_offset: libc::c_int,
    pub ar_fmag_size: libc::c_int,
}

#[derive(Debug, Copy, Clone)]
#[repr(C)]
pub struct archive_warc_defined_param {
    pub archive_read_magic: libc::c_uint,
    pub archive_state_new: libc::c_uint,
    pub enomem: libc::c_int,
    pub archive_fatal: libc::c_int,
    pub archive_ok: libc::c_int,
    pub archive_errno_misc: libc::c_int,
    pub archive_eof: libc::c_int,
    pub einval: libc::c_int,
    pub archive_format_warc: libc::c_int,
    pub ae_ifreg: libc::c_int,
}
#[derive(Debug, Copy, Clone)]
#[repr(C)]
pub struct archive_xar_defined_param {
    pub archive_read_magic: libc::c_uint,
    pub archive_state_new: libc::c_uint,
    pub enomem: libc::c_int,
    pub archive_fatal: libc::c_int,
    pub archive_ok: libc::c_int,
    pub archive_eof: libc::c_int,
    pub archive_warn: libc::c_int,
    pub archive_failed: libc::c_int,
    pub archive_errno_file_format: libc::c_int,
    pub archive_errno_misc: libc::c_int,
    pub archive_format_xar: libc::c_int,
    pub seek_set: libc::c_int,
    pub ae_ifreg: libc::c_uint,
    pub ae_ifmt : libc::c_uint,
    pub ae_ifdir: libc::c_uint,
    pub ae_iflnk: libc::c_uint,
    pub ae_ifchr : libc::c_uint,
    pub ae_ifblk: libc::c_uint,
    pub ae_ifsock : libc::c_uint,
    pub ae_ififo: libc::c_uint,
}

#[derive(Debug, Copy, Clone)]
#[repr(C)]
pub struct archive_tar_defined_param {
    pub archive_read_magic: libc::c_uint,
    pub archive_state_new: libc::c_uint,
    pub enomem: libc::c_int,
    pub archive_fatal: libc::c_int,
    pub archive_ok: libc::c_int,
    pub archive_errno_misc: libc::c_int,
    pub archive_eof: libc::c_int,
    pub einval: libc::c_int,
    pub archive_format_warc: libc::c_int,
    pub ae_ifreg: libc::c_uint,
    pub archive_failed: libc::c_int,
    pub archive_warn: libc::c_int,
    pub ae_ifdir: libc::c_uint,
    pub archive_errno_file_format: libc::c_int,
    pub archive_format_tar: libc::c_int,
    pub archive_format_tar_pax_interchange: libc::c_int,
    pub archive_format_tar_gnutar: libc::c_int,
    pub archive_format_tar_ustar: libc::c_int,
    pub archive_entry_acl_type_nfs4: libc::c_int,
    pub archive_entry_acl_type_access: libc::c_int,
    pub ae_iflnk: libc::c_uint,
    pub ae_ifchr: libc::c_uint,
    pub ae_ifblk: libc::c_uint,
    pub ae_ififo: libc::c_uint,
    pub sconv_set_opt_utf8_libarchive2x: libc::c_int,
    pub archive_entry_acl_type_default: libc::c_int,
    pub ae_symlink_type_directory: libc::c_int,
    pub archive_retry:libc::c_int,
    pub ae_symlink_type_file:libc::c_int,
}
#[derive(Copy, Clone)]
#[repr(C)]
pub struct archive_by_code_defined_param {
    pub archive_fatal: libc::c_int,
    pub archive_errno_programmer: libc::c_int,
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct archive_cab_defined_param {
    pub archive_ok: libc::c_int,
    pub archive_fatal: libc::c_int,
    pub archive_warn: libc::c_int,
    pub archive_failed: libc::c_int,
    pub archive_eof: libc::c_int,
    pub archive_errno_misc: libc::c_int,
	pub archive_errno_file_format: libc::c_int,
	pub attr_name_is_utf: libc::c_int,
	pub archive_format_cab: libc::c_int,
	pub cfheader_signature: libc::c_int,
	pub cfheader_cbcabinet: libc::c_int,
	pub cfheader_cofffiles: libc::c_int,
	pub cfheader_versionminor: libc::c_int,
	pub cfheader_cfolders: libc::c_int,
	pub cfheader_cfiles: libc::c_int,
	pub cfheader_flags: libc::c_int,
	pub cfheader_setid: libc::c_int,
	pub cfheader_icabinet: libc::c_int,
	pub cfheader_cbcfheader: libc::c_int,
	pub cfheader_cbcffolder: libc::c_int,
	pub cfheader_cbcfdata: libc::c_int,
	pub prev_cabinet: libc::c_int,
	pub next_cabinet: libc::c_int,
	pub reserve_present: libc::c_int,
	pub cffolder_coffcabstart: libc::c_int,
	pub cffolder_ccfdata: libc::c_int,
	pub cffolder_typecompress: libc::c_int,
	pub cffile_cbfile: libc::c_int,
	pub cffile_uofffolderstart: libc::c_int,
	pub cffile_ifolder: libc::c_int,
	pub cffile_date_time: libc::c_int,
	pub cffile_attribs: libc::c_int,
	pub enomem: libc::c_int,
	pub attr_rdonly: libc::c_int,
	pub ae_ifreg: libc::c_int,
	pub cfdata_cbdata: libc::c_int,
	pub cfdata_csum: libc::c_int,
	pub cfdata_cbuncomp: libc::c_int,
	pub comptype_none: libc::c_int,
	pub z_ok: libc::c_int,
	pub ifoldcontinued_prev_and_next: libc::c_int,
	pub ifoldcontinued_from_prev: libc::c_int,
	pub slot_base: libc::c_int,
	pub slot_max: libc::c_int,
	pub st_main: libc::c_int,
	pub st_rd_translation: libc::c_int,
	pub st_rd_translation_size: libc::c_int,
	pub st_rd_block_type: libc::c_int,
	pub st_rd_block_size: libc::c_int,
	pub uncompressed_block: libc::c_int,
	pub verbatim_block: libc::c_int,
	pub st_rd_verbatim: libc::c_int,
	pub st_rd_aligned_offset: libc::c_int,
	pub st_rd_alignment: libc::c_int,
	pub st_rd_r0: libc::c_int,
	pub st_rd_r1: libc::c_int,
	pub st_rd_r2: libc::c_int,
	pub st_copy_uncomp1: libc::c_int,
	pub st_copy_uncomp2: libc::c_int,
	pub st_rd_pre_main_tree_256: libc::c_int,
	pub st_main_tree_256: libc::c_int,
	pub st_rd_pre_main_tree_rem: libc::c_int,
	pub st_main_tree_rem: libc::c_int,
	pub st_rd_pre_length_tree: libc::c_int,
	pub st_length_tree: libc::c_int,
	pub st_length: libc::c_int,
	pub st_real_pos: libc::c_int,
	pub aligned_offset_block: libc::c_int,
	pub st_offset: libc::c_int,
	pub st_copy: libc::c_int,
    pub cfheader_versionmajor: libc::c_int,
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct archive_mtree_defined_param {
    pub s_iflnk: libc::c_int,
    pub s_ifsock: libc::c_int,
    pub s_ifchr: libc::c_int,
    pub s_ifblk: libc::c_int,
    pub s_ififo: libc::c_int,
    pub s_ifmt: libc::c_int,
    pub s_ifreg: libc::c_int,
    pub ae_ifreg: libc::c_int,
    pub ae_iflnk: libc::c_int,
    pub ae_ifsock: libc::c_int,
    pub ae_ifchr: libc::c_int,
    pub ae_ifblk: libc::c_int,
    pub ae_ifdir: libc::c_int,
    pub ae_ififo: libc::c_int,
    pub s_ifdir: libc::c_int,
    pub archive_ok: libc::c_int,
    pub archive_fatal: libc::c_int,
    pub archive_warn: libc::c_int,
    pub archive_failed: libc::c_int,
    pub archive_eof: libc::c_int,
    pub enomem: libc::c_int,
    pub max_line_len: libc::c_long,
    pub max_bid_entry: libc::c_int,
    pub archive_errno_misc: libc::c_int,
    pub archive_format_mtree: libc::c_int,
    pub archive_errno_file_format: libc::c_int,
    pub o_rdonly: libc::c_int,
    pub o_binary: libc::c_int,
    pub o_cloexec: libc::c_int,
    pub enoent: libc::c_int,
    pub mtree_has_optional: libc::c_int,
    pub mtree_has_device: libc::c_int,
    pub mtree_has_nochange: libc::c_int,
    pub mtree_has_gid: libc::c_int,
    pub mtree_has_gname: libc::c_int,
    pub mtree_has_uid: libc::c_int,
    pub mtree_has_uname: libc::c_int,
    pub mtree_has_mtime: libc::c_int,
    pub mtree_has_nlink: libc::c_int,
    pub mtree_has_perm: libc::c_int,
    pub mtree_has_size: libc::c_int,
    pub mtree_has_type: libc::c_int,
    pub max_pack_args: libc::c_int,
    pub archive_entry_digest_md5: libc::c_int,
    pub archive_entry_digest_rmd160: libc::c_int,
    pub archive_entry_digest_sha1: libc::c_int,
    pub archive_entry_digest_sha256: libc::c_int,
    pub archive_entry_digest_sha384: libc::c_int,
    pub archive_entry_digest_sha512: libc::c_int,
    pub archive_errno_programmer: libc::c_int,
    pub mtree_has_fflags: libc::c_int,
    pub int64_max: libc::c_longlong,
    pub int32_max: libc::c_longlong,
    pub int64_min: libc::c_longlong,
    pub int32_min: libc::c_longlong,
    pub time_t_min: libc::c_longlong,
    pub time_t_max: libc::c_longlong,
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct archive_cpio_defined_param {
    pub archive_read_magic: libc::c_uint,
    pub archive_state_new: libc::c_uint,
    pub enomem: libc::c_int,
    pub archive_errno_misc: libc::c_int,
    pub archive_ok: libc::c_int,
    pub archive_fatal: libc::c_int,
    pub archive_warn: libc::c_int,
    pub archive_failed: libc::c_int,
    pub archive_errno_file_format: libc::c_int,
    pub archive_eof: libc::c_int,
    pub ae_ifmt: libc::c_int,
    pub ae_iflnk: libc::c_uint,
    pub ae_ifreg: libc::c_int,
    pub BIN_MAGIC_OFFSET: libc::c_int,
    pub BIN_MAGIC_SIZE: libc::c_int,
    pub BIN_DEV_OFFSET: libc::c_int,
    pub BIN_DEV_SIZE: libc::c_int,
    pub BIN_INO_OFFSET: libc::c_int,
    pub BIN_INO_SIZE: libc::c_int,
    pub BIN_MODE_OFFSET: libc::c_int,
    pub BIN_MODE_SIZE: libc::c_int,
    pub BIN_UID_OFFSET: libc::c_int,
    pub BIN_UID_SIZE: libc::c_int,
    pub BIN_GID_OFFSET: libc::c_int,
    pub BIN_GID_SIZE: libc::c_int,
    pub BIN_NLINK_OFFSET: libc::c_int,
    pub BIN_NLINK_SIZE: libc::c_int,
    pub BIN_RDEV_OFFSET: libc::c_int,
    pub BIN_RDEV_SIZE: libc::c_int,
    pub BIN_MTIME_OFFSET: libc::c_int,
    pub BIN_MTIME_SIZE: libc::c_int,
    pub BIN_NAMESIZE_OFFSET: libc::c_int,
    pub BIN_NAMESIZE_SIZE: libc::c_int,
    pub BIN_FILESIZE_OFFSET: libc::c_int,
    pub BIN_FILESIZE_SIZE: libc::c_int,
    pub BIN_HEADER_SIZE: libc::c_int,

    pub ODC_MAGIC_OFFSET: libc::c_int,
    pub ODC_MAGIC_SIZE: libc::c_int,
    pub ODC_DEV_OFFSET: libc::c_int,
    pub ODC_DEV_SIZE: libc::c_int,
    pub ODC_INO_OFFSET: libc::c_int,
    pub ODC_INO_SIZE: libc::c_int,
    pub ODC_MODE_OFFSET: libc::c_int,
    pub ODC_MODE_SIZE: libc::c_int,
    pub ODC_UID_OFFSET: libc::c_int,
    pub ODC_UID_SIZE: libc::c_int,
    pub ODC_GID_OFFSET: libc::c_int,
    pub ODC_GID_SIZE: libc::c_int,
    pub ODC_NLINK_OFFSET: libc::c_int,
    pub ODC_NLINK_SIZE: libc::c_int,
    pub ODC_RDEV_OFFSET: libc::c_int,
    pub ODC_RDEV_SIZE: libc::c_int,
    pub ODC_MTIME_OFFSET: libc::c_int,
    pub ODC_MTIME_SIZE: libc::c_int,
    pub ODC_NAMESIZE_OFFSET: libc::c_int,
    pub ODC_NAMESIZE_SIZE: libc::c_int,
    pub ODC_FILESIZE_OFFSET: libc::c_int,
    pub ODC_FILESIZE_SIZE: libc::c_int,
    pub ODC_HEADER_SIZE: libc::c_int,

    pub NEWC_MAGIC_OFFSET: libc::c_int,
    pub NEWC_MAGIC_SIZE: libc::c_int,
    pub NEWC_INO_OFFSET: libc::c_int,
    pub NEWC_INO_SIZE: libc::c_int,
    pub NEWC_MODE_OFFSET: libc::c_int,
    pub NEWC_MODE_SIZE: libc::c_int,
    pub NEWC_UID_OFFSET: libc::c_int,
    pub NEWC_UID_SIZE: libc::c_int,
    pub NEWC_GID_OFFSET: libc::c_int,
    pub NEWC_GID_SIZE: libc::c_int,
    pub NEWC_NLINK_OFFSET: libc::c_int,
    pub NEWC_NLINK_SIZE: libc::c_int,
    pub NEWC_MTIME_OFFSET: libc::c_int,
    pub NEWC_MTIME_SIZE: libc::c_int,
    pub NEWC_FILESIZE_OFFSET: libc::c_int,
    pub NEWC_FILESIZE_SIZE: libc::c_int,
    pub NEWC_DEVMAJOR_OFFSET: libc::c_int,
    pub NEWC_DEVMAJOR_SIZE: libc::c_int,
    pub NEWC_DEVMINOR_OFFSET: libc::c_int,
    pub NEWC_DEVMINOR_SIZE: libc::c_int,
    pub NEWC_RDEVMAJOR_OFFSET: libc::c_int,
    pub NEWC_RDEVMAJOR_SIZE: libc::c_int,
    pub NEWC_RDEVMINOR_OFFSET: libc::c_int,
    pub NEWC_RDEVMINOR_SIZE: libc::c_int,
    pub NEWC_NAMESIZE_OFFSET: libc::c_int,
    pub NEWC_NAMESIZE_SIZE: libc::c_int,
    pub NEWC_CHECKSUM_OFFSET: libc::c_int,
    pub NEWC_CHECKSUM_SIZE: libc::c_int,
    pub NEWC_HEADER_SIZE: libc::c_ulong,

    pub AFIOL_MAGIC_OFFSET: libc::c_int,
    pub AFIOL_MAGIC_SIZE: libc::c_int,
    pub AFIOL_DEV_OFFSET: libc::c_int,
    pub AFIOL_DEV_SIZE: libc::c_int,
    pub AFIOL_INO_OFFSET: libc::c_int,
    pub AFIOL_INO_SIZE: libc::c_int,
    pub AFIOL_INO_M_OFFSET: libc::c_int,
    pub AFIOL_MODE_OFFSET: libc::c_int,
    pub AFIOL_MODE_SIZE: libc::c_int,
    pub AFIOL_UID_OFFSET: libc::c_int,
    pub AFIOL_UID_SIZE: libc::c_int,
    pub AFIOL_GID_OFFSET: libc::c_int,
    pub AFIOL_GID_SIZE: libc::c_int,
    pub AFIOL_NLINK_OFFSET: libc::c_int,
    pub AFIOL_NLINK_SIZE: libc::c_int,
    pub AFIOL_RDEV_OFFSET: libc::c_int,
    pub AFIOL_RDEV_SIZE: libc::c_int,
    pub AFIOL_MTIME_OFFSET: libc::c_int,
    pub AFIOL_MTIME_SIZE: libc::c_int,
    pub AFIOL_MTIME_N_OFFSET: libc::c_int,
    pub AFIOL_NAMESIZE_OFFSET: libc::c_int,
    pub AFIOL_NAMESIZE_SIZE: libc::c_int,
    pub AFIOL_FLAG_OFFSET: libc::c_int,
    pub AFIOL_FLAG_SIZE: libc::c_int,
    pub AFIOL_XSIZE_OFFSET: libc::c_int,
    pub AFIOL_XSIZE_SIZE: libc::c_int,
    pub AFIOL_XSIZE_S_OFFSET: libc::c_int,
    pub AFIOL_FILESIZE_OFFSET: libc::c_int,
    pub AFIOL_FILESIZE_SIZE: libc::c_int,
    pub AFIOL_FILESIZE_C_OFFSET: libc::c_int,
    pub AFIOL_HEADER_SIZE: libc::c_int,
    pub cpio_magic: libc::c_int,
    pub archive_format_cpio_svr4_nocrc: libc::c_int,
    pub archive_format_cpio_svr4_crc: libc::c_int,
    pub archive_format_cpio_afio_large: libc::c_int,
    pub archive_format_cpio_posix: libc::c_int,
    pub archive_format_cpio_bin_le: libc::c_int,
    pub archive_format_cpio_bin_be: libc::c_int,
}

lazy_static! {
    pub static ref ARCHIVE_EMPTY_DEFINED_PARAM: archive_empty_defined_param =
        unsafe { get_archive_empty_defined_param() };
    pub static ref ARCHIVE_ISO9660_DEFINED_PARAM: archive_iso9660_defined_param =
        unsafe { get_archive_iso9660_defined_param() };
    pub static ref ARCHIVE_LHA_DEFINED_PARAM: archive_lha_defined_param =
        unsafe { get_archive_lha_defined_param() };
    pub static ref ARCHIVE_RAW_DEFINED_PARAM: archive_raw_defined_param =
        unsafe { get_archive_raw_defined_param() };
    pub static ref ARCHIVE_RAR_DEFINED_PARAM: archive_rar_defined_param =
        unsafe { get_archive_rar_defined_param() };
    pub static ref ARCHIVE_RAR5_DEFINED_PARAM: archive_rar5_defined_param =
        unsafe { get_archive_rar5_defined_param() };
    pub static ref ARCHIVE_AR_DEFINED_PARAM:archive_ar_defined_param=
        unsafe { get_archive_ar_defined_param() };
    pub static ref ARCHIVE_WARC_DEFINED_PARAM:archive_warc_defined_param=
        unsafe {get_archive_warc_defined_param()};
    pub static ref ARCHIVE_XAR_DEFINED_PARAM:archive_xar_defined_param=
        unsafe {get_archive_xar_defined_param()};

    pub static ref ARCHIVE_TAR_DEFINED_PARAM:archive_tar_defined_param=
        unsafe {get_archive_tar_defined_param()};
    pub static ref ARCHIVE_ACL_DEFINED_PARAM: archive_acl_defined_param =
        unsafe { get_archive_acl_defined_param() };
    pub static ref ARCHIVE_BY_CODE_DEFINED_PARAM: archive_by_code_defined_param =
        unsafe { get_archive_by_code_defined_param() };
    pub static ref ARCHIVE_CAB_DEFINED_PARAM: archive_cab_defined_param =
        unsafe { get_archive_cab_defined_param() };
    pub static ref ARCHIVE_MTREE_DEFINED_PARAM: archive_mtree_defined_param =
        unsafe { get_archive_mtree_defined_param() };
    pub static ref ARCHIVE_CPIO_DEFINED_PARAM: archive_cpio_defined_param =
        unsafe { get_archive_cpio_defined_param() };
}
